// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0fHNlimh_nFXGIjvgOoGgg4U3umjXkQY',
    appId: '1:611824126895:web:96d8927863c1159e837d5a',
    messagingSenderId: '611824126895',
    projectId: 'walltutorial-f7708',
    authDomain: 'walltutorial-f7708.firebaseapp.com',
    storageBucket: 'walltutorial-f7708.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFhfsMi3kTCZwgF-KcmpDfPQnS_mpwRm8',
    appId: '1:611824126895:android:b167a31339b7985e837d5a',
    messagingSenderId: '611824126895',
    projectId: 'walltutorial-f7708',
    storageBucket: 'walltutorial-f7708.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXQ4ei1XNsMdObRNeiTHwz4ccAYVfjGR0',
    appId: '1:611824126895:ios:1fe60fe6f45a1825837d5a',
    messagingSenderId: '611824126895',
    projectId: 'walltutorial-f7708',
    storageBucket: 'walltutorial-f7708.appspot.com',
    iosClientId: '611824126895-mbhi502j2ecu29if8bbgqm4l67n5rv4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMeadia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXQ4ei1XNsMdObRNeiTHwz4ccAYVfjGR0',
    appId: '1:611824126895:ios:457b6a6d0ce44f8d837d5a',
    messagingSenderId: '611824126895',
    projectId: 'walltutorial-f7708',
    storageBucket: 'walltutorial-f7708.appspot.com',
    iosClientId: '611824126895-o20m10l23dd9gpbt5l743qk9f4g4tjok.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMeadia.RunnerTests',
  );
}
